# run first $docker-compose up -d --force-recreate in folder "traefik", at this time network "traefik_webgateway" does not exists
# run this again with $docker-compose up -d --force-recreate
# troubleshooting with $docker logs -f docker_proxy
# log into container $docker exec -it docker_proxy /bin/sh

#Used_tags:
#$Traefik\Linux
#$Traefik\Windows 10 Pro
#$Traefik\domain 
#- dev.local comes from ../config/traefik.toml {docker.domain = "dev.local"}
#Env_File
#you can debug with $docker-compose config

version: '3.7'


networks:
  webgateway:
    driver: bridge

services:
  my_proxy:
    env_file:                                           #Env_File
      - ../version/.env                                 #Env_File
    #source https://github.com/containous/traefik
    #image: traefik:${TRAEFIK_VERSION}                   #Env_File
    image: traefik:v1.7.12-alpine
    #you can set traefik with command, but I prefare use "traefik.toml"
    container_name: docker_proxy
    # command:
    #   - "--api" #dashboard enabled
    #   - "--entrypoints=Name:http Address::90"         #port where running proxy
    #   - "--defaultentrypoints=http"                   #only http://
    #   - "--docker"                                    #provider
    #   - "--docker.domain=dev.local"                   #domain
    #   - "--logLevel=DEBUG"
    #   - "--entryPoints=Name:dashboard Address::8090"  #http://dev.local:8090/dasboard
      
      
      
      
   
    networks:
      - webgateway
    #exposed ports on host 90=proxy; 8090=http://localhost:8090/dasboard
    #comes from trafik.toml
    ports:
      - target: 90
        published: 90
        mode: host
      - target: 443
        published: 443
        mode: host
      - target: 8090
        published: 8090
        mode: host
    
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./config/traefik.toml:/traefik.toml        #Windows 10 Pro
      #- $PWD/data/config/traefik.toml:/traefik.toml    #Traefik\Linux
      #- $PWD/acme.json:/acme.json                      #lets encrypt
      #if you want ignore default configuration
      #- /dev/null:/traefik.toml                        


    labels:
      - "traefik.enable=true"
      - "traefik.port=8090"
      - "traefik.frontend.rule=Host:monitor.dev.local"  #Traefik\domain
      - "traefik.docker.network=webgateway"



  my_pontainer:
    image: portainer/portainer
    container_name: docker_portainer
    restart: always 
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./data/portainer:/data    
   # environment:

    networks:
      - webgateway

    labels:
      - traefik.backend=portainer
      - traefik.docker.network=traefik_webgateway
      - traefik.frontend.rule=Host:portainer.dev.local #Traefik\domain
      - traefik.port=9000
      - traefik.enable=true
      - traefik.portainer.frontend.rule=PathPrefix:/portainer
      
    ports:
      - target: 9000
        published: 9000
        mode: host

    command: -H unix:///var/run/docker.sock