# https://github.com/BytemarkHosting/configs-jenkins-docker/blob/master/docker-compose.yml
# https://blog.linuxserver.io/2018/02/03/using-traefik-as-a-reverse-proxy-with-docker/
# https://github.com/Starttoaster/docker-traefik/blob/master/tpl/traefik.toml.tpl
# https://blog.linuxserver.io/2019/04/25/letsencrypt-nginx-starter-guide/#reverseproxy
# https://jtreminio.com/blog/traefik-on-docker-for-web-developers/
# https://www.digitalocean.com/community/tutorials/how-to-use-traefik-as-a-reverse-proxy-for-docker-containers-on-debian-9
# http://blog.francoisfaubert.com/2018/06/11/dockerized-jenkins-with-traefik-2.html
# https://www.praqma.com/stories/Proxying-Docker-containers-with-ease/
# https://www.tikalk.com/posts/2017/10/10/traefik-basics-with-docker-compose/

# run first $docker-compose up -d --force-recreate in folder "traefik", at this time network "traefik_webgateway" does not exists
# run this again with $docker-compose up -d --force-recreate
# troubleshooting with $docker logs -f docker_proxy
# log into container $docker exec -it docker_proxy /bin/sh

#Used_tags:
#$Traefik\Linux
#$Traefik\Windows 10 Pro
#$Traefik\domain 
#- dev.local comes from ../config/traefik.toml {docker.domain = "dev.local"}

version: '3.7'


networks:
  webgateway:
    driver: bridge

services:
  proxy:
    #source https://github.com/containous/traefik
    image: traefik:v1.7.12-alpine
    #you can set traefik with command, but I prefare use "traefik.toml"
    container_name: docker_proxy
    # command:
    #   - "--api" #dashboard enabled
    #   - "--entrypoints=Name:http Address::90"         #port where running proxy
    #   - "--defaultentrypoints=http"                   #only http://
    #   - "--docker"                                    #provider
    #   - "--docker.domain=dev.local"                   #domain
    #   - "--logLevel=DEBUG"
    #   - "--entryPoints=Name:dashboard Address::8090"  #http://dev.local:8090/dasboard
      
      
      
      
   
    networks:
      - webgateway
    #exposed ports on host 90=proxy; 8090=http://localhost:8090/dasboard
    #comes from trafik.toml
    ports:
      - target: 90
        published: 90
        mode: host
      - target: 443
        published: 443
        mode: host
      - target: 8090
        published: 8090
        mode: host
    
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./config/traefik.toml:/traefik.toml        #Windows 10 Pro
      #- $PWD/data/config/traefik.toml:/traefik.toml    #Traefik\Linux
      #- $PWD/acme.json:/acme.json                      #lets encrypt
      #if you want ignore default configuration
      #- /dev/null:/traefik.toml                        


    labels:
      - "traefik.enable=true"
      - "traefik.port=8090"
      - "traefik.frontend.rule=Host:monitor.dev.local"  #Traefik\domain
      - "traefik.docker.network=webgateway"

